name: Update

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  empty_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "Jorge Ruvalcaba"
          git config user.email "jorgeruvalcabav@gmail.com"

      - name: Commit changes
        run: |
          git commit --allow-empty -m ""

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
